//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppStoreAccounting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int id { get; set; }
        public int idCategory { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerAddress { get; set; }
        public long Price { get; set; }
        public int QuantityStore { get; set; }
        public int QuantityWarehouse { get; set; }
        public string NameProducts { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual LoadCategory LoadCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
